### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [sithmel/posthtml-plugin-link-preload#1]
@sithmel  Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by sithmel** [comment]
I am happy to add it to the plugin list (I am going to create a PR).
If you won't mind I will keep it in this repo

**Comment by sithmel** [comment]
And congrats for the excellent library @Scrum 😄

**Comment by Scrum** [comment]
@sithmel Hi
> If you won't mind I will keep it in this repo

 I think that any decision you make regarding your products is correct)) 

Let me know if you change your mind or need something

**Comment by Scrum** [comment]
> And congrats for the excellent library

I'm glad that someone needs him))
